FROM mysql

ENV MYSQL_USER=acoldbottle
ENV MYSQL_PASSWORD=88888888
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=acoldbottledb

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
